export const cardImages = [
  { src: "/img/1.png", name: "firstImg" },
  { src: "/img/2.png", name: "secondImg" },
  { src: "/img/3.png", name: "thirdtImg" },
  { src: "/img/4.png", name: "fourthImg" },
  { src: "/img/5.png", name: "fifthImg" },
  { src: "/img/6.png", name: "sixthImg" },
  { src: "/img/7.png", name: "seventhImg" },
  { src: "/img/8.png", name: "eighthImg" },
  { src: "/img/9.png", name: "ninthImg" },
  { src: "/img/10.png", name: "tenthImg" },
  { src: "/img/11.png", name: "eleventhImg" },
  { src: "/img/12.png", name: "twelveImg" },
  { src: "/img/13.png", name: "thirteenthImg" },
  { src: "/img/14.png", name: "fourteenthImg" },
  { src: "/img/15.png", name: "fifteenthImg" },
  { src: "/img/16.png", name: "sixteenthImg" },
  { src: "/img/17.png", name: "seventeenthImg" },
  { src: "/img/18.png", name: "eighteenthImg" },
];
